
 const essay = `

Coming of Age Story/Speech
For those of you who don’t know, I’m a middle child. My older sister, Marianne (yes, our names rhyme) is 23, and my younger brother, Matt, is 15. My sister and I have always been very different: she was always the outgoing one, the impatient one, the social butterfly, and the more serious athlete. I tended to be more reserved, analytical, and (I like to think) a little more “chill” than her. Take this classic example of our differences: One night at dinner after an especially frustrating chemistry assignment in her junior year at KO, my sister exclaimed, “I’m so done with this science stuff. Why are atoms even important? This crap has nothing to do with my actual life.” To which I immediately and enthusiastically responded, “How could you say they’re not relevant? They make up everything!” We then proceeded to briefly argue about the relevance of chemistry. This isn’t to imply that my sister isn’t smart; quite the contrary. She was always very smart, she just happened to be a bit more practical and impatient than me. But I digress. The point of all this comparison is that I thought my sister was the ideal way to be. She loved people and people loved her. I wished I could be more outgoing like her, and starting when I was about 10, I basically idolized Marianne in every way.

Unfortunately, because of our age gap, she had no patience for my “annoying little sister” vibe until I was about 12 and she stopped acting like a bitchy teenager. Around that same time, she was going into her senior year of high school and had a boyfriend named Mike. I got along well with Mike because he was nice to me and always brought me presents on holidays and my birthday. One time, he even got me a signed David Archuletta CD, which was a big freakin deal, since I was still in my intense American Idol phase. My sister dated him for two years until they graduated high school, and I have some pretty fond memories of awkward situations that dealt with an oblivious 5th/6th grade Julianne discovering secret information about their weekend activities.

Most of those awkward situations took place in the basement at my old house. Mike would come over a lot, sometimes on school nights, and whenever he was over, the basement was off limits. My sister made that very clear. And I respected it, since I spent most of my time in my room anyway. Most nights I went to bed pretty early so I didn’t have any reason to be in the basement that late. One night, though, I was up late (10:30, haha) watching a movie in my room when I heard Mike’s car leave and my sister go up to bed. I decided for some reason that I wanted to finish watching my movie on the basement TV, so I went downstairs since the coast was clear. Don’t worry; this isn’t going where you might think it’s going. The basement was actually empty at that point and my sister was actually in bed. The forgotten brown paper bag I found on the basement couch, though, was equally as alarming to me as if I had walked in on something else. At first, I was just going to throw the bag away without a second thought, but then I decided to look inside. There were a few glass bottles that said “Smirnoff Ice,” and they were strawberry flavored I think. At that point, I didn’t even know what Smirnoff Ice was, and I thought it was a fancy type of soda. That is, until I looked closer: “4.5% alcohol by volume” the front label said.

My heart skipped a beat. I froze. My sister was drinking…alcohol?!? Alcohol is evil! Alcohol is poison! What if she’s an alcoholic?? Just say no!!!

This all sounds utterly ridiculous as an 18 year old now, but at the time, I honestly was so crushed. I didn’t know what to do. How could someone who seemed so perfect be hiding so much from me? How could she do something bad? I freaked out and hid the bag in a cabinet in the basement, so my mom wouldn’t find it if she went downstairs in the morning. Despite my extreme and naive views regarding my sister drinking one Smirnoff Ice, I didn’t want her to get in trouble. Also, I thought, if she knew that I helped her out, she might think I was cool or mature, and I’d finally get her full approval as a sister and as a friend.

That’s what I hoped, at least. After I put the bag of empties in the cabinet, I went upstairs, holding back tears. I knocked on my sister’s bedroom door and told her that she had left the bag downstairs but that I hid it and that she could get it tomorrow. She replied with a casual smile and “Thanks, sorry for leaving that, please don’t mention this to mom and dad.” I responded “Of course not” and went back to my room. As soon as the door was shut, I ran to my bed and started to cry. And I mean cry. I tried to stay as quiet as I could out of fear that my family would hear me, but boy was I crying. I’m a crier, in case you couldn’t tell.

I didn’t just cry, though. I prayed to Jesus. I held my own solitary prayer session for my sister in my room. It’s ok to laugh, seriously. It’s even funnier if you know that now, I pretty much am an agnostic atheist and refer to Jesus as “my man JC.” At the time, though, I felt like I need to talk to somebody about the fact that my worldview was shattered, and Jesus seemed like a good enough option. I remember begging Jesus to keep my sister safe and to make sure she wouldn’t get in trouble or become an alcoholic because I loved her. I also asked Jesus how a good person could do something bad, because I didn’t understand why a good person would do something illegal on purpose. Now, of course, I understand her side of the story (I like to have fun from time to time just as much as the next 18 year old) and realize how outrageous my polarized moral compass was; but surprisingly, I didn’t revise that moral compass very much until somewhat recently.

Now I’d like to time travel a little bit, create a wrinkle in time if you will :), but without Marshall Barnes or a fan with a strobe light. Flash forward to this past fall of our senior year. Again, but this time in a new house, I found myself hysterically silent-crying in my room. To keep things simple and spare myself excessive emotion, I’ll just say that some older friends of mine pressured me into situations that I wasn’t comfortable with involving alcohol and drugs, and I made some dumb decisions to keep from being the straight-edged person that I feared I would become and that my sister never was. This whole scenario contributed to my first personal experience with depression and anxiety. I developed a fear of driving, even though I’d had my license for over a year at that point, and I began to treat every decision like it was literally life or death. I completely lost trust in myself. It’s hard to explain, but it was kind of like my mind fixated on everything that could possibly go wrong, then convinced me that things should have gone wrong, and as a result, I felt like I didn’t deserve anything that went right. It was exhausting to get up every day and wonder what I would do next to screw up. And I couldn’t help it. It was a response to trauma that affected the way I thought, and I would wonder why other people couldn’t feel the same hyper-awareness that I felt every minute. Why couldn’t other people see that driving was so dangerous? Didn’t people know that I had such power to do damage to the people I loved? What if I screwed up big time and I let people down? I felt like I was “rainbow wheeling” as Asha likes to put it, and any “click” that I attempted to make could crash my whole computer forever.

It all essentially boiled down to a fear of making mistakes. Still struggling like the 11 year old, Jesus-worshiping me from that previous moment in time, I have only recently accepted that imperfections are ok, and the best way to deal with inevitable mistakes is to learn from them. In the words of the great Hannah Montana, “Everybody makes mistakes. Everybody has those days.” Up until recently, it has always been so easy to make the right decision and avoid serious consequences from mistakes because I was so sheltered and on a pretty reliable, pre-determined path to the goal of college or adulthood or whatever goal I had in mind. When things got to the point that my friends were worried about my mental health during the winter, I decided to go talk to someone and get some help dealing with my rainbow-wheeling fears and excessive crying. I’m so glad I did. For the past few months, I’ve felt so much better than I have in a long time. I feel like a more complete person knowing that I’ve made it through one of my first major personal struggles. Even though I’ll never exactly be able to forget how much I struggled with something so deceptively simple and fundamental as “it’s ok to make mistakes,” I know now that a speed bump on whatever path I’m taking is just that: a speed bump. It’s not the edge of a cliff. One of my favorite quotes is one that I think Salvo used on his yearbook page. Robert Frost said, “In three words I can sum up everything I’ve learned about life: It goes on.” It does go on, and it gets better.

Proudly powered by WordPress`

export default essay;